dist: jammy
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
  - "3.11-dev"
  - "nightly"  # nightly build
addons:
  apt:
    packages:
    - libsnappy-dev
# Pycodestyle part
# needed to work correctly with Python 3 shebang
env: SKIP_INTERPRETER=true
install:
  - pip install pycodestyle
  - pip install pydocstyle
  - pip install pytest-cov
script:
  - make style
  - make doc-check
  - rm tmp.md